/*
 * The Doctor class that implement the doctor interfaces and function,
 * it has interractions with other class and functions in this package
 */
package com.aljebraschool.pharmacy;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        medCentreRefTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        officeNumTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        officeNum2TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        docFirstnameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        faxNumTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        docSurnameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        medCtrNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        patientNHSNumTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        patientIDTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emisNumTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AddCentreTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gpaAppointTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        postCodeTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        docNhsNoTextField = new javax.swing.JTextField();
        TabletComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Medical Center Ref");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        medCentreRefTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(medCentreRefTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 300, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Doctor's NHS NO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Office Phone No 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        officeNumTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(officeNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 300, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Doctor's Ref No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Office Phone No 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        officeNum2TextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(officeNum2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 300, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Firstname");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        docFirstnameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(docFirstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Fax No");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        faxNumTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(faxNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 300, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Surname");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        docSurnameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(docSurnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Email Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 300, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Medical Center Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        medCtrNameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(medCtrNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Patient NHS No");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        patientNHSNumTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(patientNHSNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 300, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Patient ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        patientIDTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(patientIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 230, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("EMIS No");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        emisNumTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(emisNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 300, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Address of Center");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        AddCentreTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(AddCentreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("GP Appointment Ref");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        gpaAppointTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(gpaAppointTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 300, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Post Code");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        postCodeTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(postCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 230, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 120, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Pharmacy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("GP Appointment");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 140, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Patient");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 140, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Payment");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 130, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Pharmacy Office ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 130, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Login");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1300, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc Ref No", "Doc NHS No", "Firstname ", "Surname", "Med Center Name", "Patient ID", "Address of Center", "Post Code", "Med Center Ref", "Office Phone No 1", "Office Phone No 2", "Fax No", "Email Address", "Patient NHS No", "EMIS No", "GP Appointment Ref"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 1300, 180));

        docNhsNoTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        docNhsNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docNhsNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(docNhsNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 230, -1));

        TabletComboBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TabletComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor's Ref", "Dr1231", "Dr3456", "Dr0987", "" }));
        TabletComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabletComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(TabletComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //Exit button component 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //check if JOptionPane dialog box is a yes option which is 0
        if(JOptionPane.showConfirmDialog(null,"Confirm if you want to exit", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_NO_OPTION)
            //if yes
            System.exit(0); // then exit the program
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); //downcasting the superclass variable of class JTable (jTable1) to the variable of the subclass (model)

        //annonymous inner class to add items to the table component
        model.addRow( new Object[]
            {
                //add items from each component to the table component
                TabletComboBox.getSelectedItem().toString(),
                docNhsNoTextField.getText(),
                docFirstnameTextField.getText(),
                docSurnameTextField.getText(),
                medCtrNameTextField.getText(),
                patientIDTextField.getText(),
                AddCentreTextField.getText(),
                postCodeTextField.getText(),
                medCentreRefTextField.getText(),
                officeNumTextField.getText(),
                officeNum2TextField.getText(),
                faxNumTextField.getText(),
                emailTextField.getText(),
                patientNHSNumTextField.getText(),
                emisNumTextField.getText(),
                gpaAppointTextField.getText(),

            }

        );

    }//GEN-LAST:event_jButton2ActionPerformed

    //when delete button is pressed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();  //downcasting the superclass variable of class JTable (jTable1) to the variable of the subclass (model)
        if(jTable1.getSelectedRow() == -1)       //check if no row is selected by comparing it returned index to -1
        {
            if(jTable1.getRowCount() == 0){      //check if the table has no row by comparing it with 0

                //if these two conditions are true then print message on the JOptionPane
                JOptionPane.showMessageDialog(null, "No data to delete", "Student Result System", JOptionPane.NO_OPTION );
            }
            else //if there are rows in the table, then print this using JOptionPane
            JOptionPane.showMessageDialog(null, "Select a row to delete", "Student Result System", JOptionPane.OK_OPTION);
        }
        else //if you have selected a row then remove it
        model.removeRow(jTable1.getSelectedRow());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    //when this button is pressed
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        Login myLogin = new Login(); //create the object of class login
        myLogin.setVisible(true);   //show class login window

    }//GEN-LAST:event_jButton9ActionPerformed

    private void docNhsNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docNhsNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docNhsNoTextFieldActionPerformed

        //when this button is pressed
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Pharmacy myPharmacy = new Pharmacy(); //create the object of class Pharmacy
        myPharmacy.setVisible(true);        //show class login window

    }//GEN-LAST:event_jButton4ActionPerformed

    //when the comboBox component is pressed
    private void TabletComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabletComboBoxActionPerformed
       //if item selected is Dr1231
        if (TabletComboBox.getSelectedItem().equals("Dr1231")) { 
         //set the following text for each component 
            docNhsNoTextField.setText("1234");
            docFirstnameTextField.setText("Ishaq");
            docSurnameTextField.setText("Ojodu");
            medCtrNameTextField.setText("Modular Specialist Hospital");
            patientIDTextField.setText("000123");
            AddCentreTextField.setText("Esso Ondo City");
            postCodeTextField.setText("0983");

            medCentreRefTextField.setText("2345");
            officeNumTextField.setText("08132559222");
            officeNum2TextField.setText("08189445255");
            faxNumTextField.setText("01-56752");
            emailTextField.setText("ibidunniaidan@gmail.com");
            patientNHSNumTextField.setText("09876");
            emisNumTextField.setText("P001");
            gpaAppointTextField.setText("12345");

        
       }
               // else if item selected is Dr3456
      else if (TabletComboBox.getSelectedItem().equals("Dr3456")) { 
                 //set the following text for each component 
            docNhsNoTextField.setText("1234");
            docFirstnameTextField.setText("Abiola");
            docSurnameTextField.setText("Akingbemisilu");
            medCtrNameTextField.setText("Medical Sciences");
            patientIDTextField.setText("900123");
            AddCentreTextField.setText("Sabo Ondo City");
            postCodeTextField.setText("0083");

            medCentreRefTextField.setText("2345");
            officeNumTextField.setText("08132559226");
            officeNum2TextField.setText("08189445295");
            faxNumTextField.setText("01-96752");
            emailTextField.setText("aljebraschoolofthougth@gmail.com");
            patientNHSNumTextField.setText("09879");
            emisNumTextField.setText("P002");
            gpaAppointTextField.setText("19845");

        
       }
        // else if item selected is Dr0987
        else if (TabletComboBox.getSelectedItem().equals("Dr0987")) { 
           //set the following text for each component 
            docNhsNoTextField.setText("1774");
            docFirstnameTextField.setText("Ridwan");
            docSurnameTextField.setText("Ibidunni");
            medCtrNameTextField.setText("Aljebra school");
            patientIDTextField.setText("900993");
            AddCentreTextField.setText("New York City");
            postCodeTextField.setText("0993");

            medCentreRefTextField.setText("2345");
            officeNumTextField.setText("08135559226");
            officeNum2TextField.setText("08189445655");
            faxNumTextField.setText("04-96752");
            emailTextField.setText("aljebraschoolofthougth@gmail.com");
            patientNHSNumTextField.setText("09879");
            emisNumTextField.setText("P002");
            gpaAppointTextField.setText("19845");

        
       }
       
        // else if item selected is Select Doctor's Ref      
       else if (TabletComboBox.getSelectedItem().equals("Select Doctor's Ref")) { 
           //set the following text for each component 
            docNhsNoTextField.setText("");
            docFirstnameTextField.setText("");
            docSurnameTextField.setText("");
            medCtrNameTextField.setText("");
            patientIDTextField.setText("");
            AddCentreTextField.setText("");
            postCodeTextField.setText("");

            medCentreRefTextField.setText("");
            officeNumTextField.setText("");
            officeNum2TextField.setText("");
            faxNumTextField.setText("");
            emailTextField.setText("");
            patientNHSNumTextField.setText("");
            emisNumTextField.setText("");
            gpaAppointTextField.setText("");

        
       }
       
       
       
    }//GEN-LAST:event_TabletComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddCentreTextField;
    private javax.swing.JComboBox<String> TabletComboBox;
    private javax.swing.JTextField docFirstnameTextField;
    private javax.swing.JTextField docNhsNoTextField;
    private javax.swing.JTextField docSurnameTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField emisNumTextField;
    private javax.swing.JTextField faxNumTextField;
    private javax.swing.JTextField gpaAppointTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField medCentreRefTextField;
    private javax.swing.JTextField medCtrNameTextField;
    private javax.swing.JTextField officeNum2TextField;
    private javax.swing.JTextField officeNumTextField;
    private javax.swing.JTextField patientIDTextField;
    private javax.swing.JTextField patientNHSNumTextField;
    private javax.swing.JTextField postCodeTextField;
    // End of variables declaration//GEN-END:variables
}
