/* The Login class is the first window that give access to other windows,
 * it has interractions with other classes
 */
package com.aljebraschool.pharmacy;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordButton = new javax.swing.JLabel();
        usernameButton = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doctorButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        pharmacyButton = new javax.swing.JButton();
        gpaButton = new javax.swing.JButton();
        pharOfficeButton = new javax.swing.JButton();
        surveyButton = new javax.swing.JButton();
        hospitalButton = new javax.swing.JButton();
        specialistButton = new javax.swing.JButton();
        pharmacistButton = new javax.swing.JButton();
        consultantButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("Login Systems");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 340, 50));

        usernameTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 230, -1));

        passwordButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordButton.setText("Password");
        jPanel2.add(passwordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, -1));

        usernameButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameButton.setText("Username");
        jPanel2.add(usernameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));

        loginButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 40));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        cancelButton.setText("Cancel ");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 170, 40));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 170, 40));

        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel2.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 155, 230, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 660, 320));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Pharmacy Managment Systems");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 830, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 1260, 80));

        doctorButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        doctorButton.setText("Doctor");
        doctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doctorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 240, 50));

        patientButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        patientButton.setText("Patient");
        getContentPane().add(patientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 240, 50));

        paymentButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        paymentButton.setText("Payment");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 240, 50));

        pharmacyButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pharmacyButton.setText("Pharmacy");
        pharmacyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pharmacyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 240, 50));

        gpaButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gpaButton.setText("GPAppointment ");
        gpaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gpaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 240, 50));

        pharOfficeButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pharOfficeButton.setText("Pharmacy Office");
        pharOfficeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharOfficeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pharOfficeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 240, 50));

        surveyButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        surveyButton.setText("Survey");
        getContentPane().add(surveyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 200, 50));

        hospitalButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        hospitalButton.setText("Hospital");
        hospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hospitalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 220, 200, 50));

        specialistButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        specialistButton.setText("Specialist");
        getContentPane().add(specialistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 280, 200, 50));

        pharmacistButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pharmacistButton.setText("Pharmacist");
        getContentPane().add(pharmacistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, 200, 50));

        consultantButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        consultantButton.setText("Consultant");
        consultantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultantButtonActionPerformed(evt);
            }
        });
        getContentPane().add(consultantButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, 200, 50));

        helpButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        getContentPane().add(helpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 460, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //when this button is pressed
    private void pharmacyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyButtonActionPerformed
        Pharmacy myPharmacy = new Pharmacy(); //create the object of class Pharmacy
        myPharmacy.setVisible(true);           //show this window

    }//GEN-LAST:event_pharmacyButtonActionPerformed

    private void pharOfficeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharOfficeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pharOfficeButtonActionPerformed

    private void hospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButtonActionPerformed

    //setting the visibility of components on the main window (JFrame) to false by default
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       //all components are not displayed by default
        doctorButton.setEnabled(false);
        pharmacyButton.setEnabled(false);
        patientButton.setEnabled(false);
        paymentButton.setEnabled(false);
        gpaButton.setEnabled(false);
        pharOfficeButton.setEnabled(false);
        surveyButton.setEnabled(false);
        hospitalButton.setEnabled(false);
        specialistButton.setEnabled(false);
        consultantButton.setEnabled(false);
        pharmacistButton.setEnabled(false);
        helpButton.setEnabled(false);
        
    }//GEN-LAST:event_formWindowActivated
        //Exit button component 
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
           
        //check if JOptionPane dialog box is a yes option which is 0    
        if(JOptionPane.showConfirmDialog(null,"Confirm if you want to exit", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION) 
                  == JOptionPane.YES_NO_OPTION)
            //if yes
              System.exit(0); // then exit the program
              
    }//GEN-LAST:event_exitButtonActionPerformed

 //clear the content of these components when this componet is pressed
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        usernameTextField.setText("");
        PasswordField.setText("");
       
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        
    }//GEN-LAST:event_PasswordFieldActionPerformed
    int attempt = 3; //variable to control user attempts, user has only three attempts initially
    
    //componet that will make the window components visible again
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    //local variables to get inputs in these components
    String username = usernameTextField.getText();
    String password = PasswordField.getText();
   
//check if contents of username and password equals to the given strings
    if ( username.contains("aljebra") && password.contains("aljebra2117"))
    {   //if yes
        
        usernameTextField.setText(""); //clear this component
        PasswordField.setText("");      //clear this component
        
        //make the components on the window (JFrame) visible again 
        doctorButton.setEnabled(true);
        pharmacyButton.setEnabled(true);
        patientButton.setEnabled(true);
        paymentButton.setEnabled(true);
        gpaButton.setEnabled(true);
        pharOfficeButton.setEnabled(true);
        surveyButton.setEnabled(true);
        hospitalButton.setEnabled(true);
        specialistButton.setEnabled(true);
        consultantButton.setEnabled(true);
        pharmacistButton.setEnabled(true);
        helpButton.setEnabled(true);

     
    }
    //if condition is false
    else if (!( username.contains("aljebra") && password.contains("aljebra2117")))
    {
        usernameTextField.setText("");  //clear this component
        PasswordField.setText("");     //clear this component
        
        //make the components on the window (JFrame) not visible         
        doctorButton.setEnabled(false);
        pharmacyButton.setEnabled(false);
        patientButton.setEnabled(false);
        paymentButton.setEnabled(false);
        gpaButton.setEnabled(false);
        pharOfficeButton.setEnabled(false);
        surveyButton.setEnabled(false);
        hospitalButton.setEnabled(false);
        specialistButton.setEnabled(false);
        consultantButton.setEnabled(false);
        pharmacistButton.setEnabled(false);
        helpButton.setEnabled(false);
        
        --attempt;  //predecrement the attempt variable for 3
        
        //show JPane window to tell the user the number of attempts remaining
        JOptionPane.showMessageDialog(null, "Remaining attempts: " + attempt,  "Pharmacy Management Systems", JOptionPane.INFORMATION_MESSAGE);
        
        
        if( attempt == 0) //3 attempts exhausted 
            System.exit(0); //exit the system

    }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    //when this button is pressed
    private void doctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorButtonActionPerformed

        Doctor myDoctor = new Doctor(); //create the doctor object
        myDoctor.setVisible(true);     //show doctor class window
    }//GEN-LAST:event_doctorButtonActionPerformed

    private void gpaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpaButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void consultantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultantButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton consultantButton;
    private javax.swing.JButton doctorButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton gpaButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton hospitalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordButton;
    private javax.swing.JButton patientButton;
    private javax.swing.JButton paymentButton;
    private javax.swing.JButton pharOfficeButton;
    private javax.swing.JButton pharmacistButton;
    private javax.swing.JButton pharmacyButton;
    private javax.swing.JButton specialistButton;
    private javax.swing.JButton surveyButton;
    private javax.swing.JLabel usernameButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
