/*
 * The Pharmacy class that implement the pharmacy interfaces and function,
 * it has interractions with other class and functions in this package
 */
package com.aljebraschool.pharmacy;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Pharmacy extends javax.swing.JFrame {

    /**
     * Creates new form Pharmacy
     */
    public Pharmacy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sideEffectTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        refTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        infoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        storageTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        doseTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        adminTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tabletTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        machineTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lotTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        medTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        issusedDateTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        expDateTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        docNhsNumTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dailyDoseTextField = new javax.swing.JTextField();
        TabletComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Possible Side Effects:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        sideEffectTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(sideEffectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 300, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Reference No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        refTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        refTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(refTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 230, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Further Information: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        infoTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(infoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 300, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Name of Tablet: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Storage Advice: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        storageTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(storageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 300, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Dose (mg):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        doseTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(doseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Administrations: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));

        adminTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(adminTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 300, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Number of Tables:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        tabletTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(tabletTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Driving and Using Machines:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, -1, -1));

        machineTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(machineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 300, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("LOT: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        lotTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(lotTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 230, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("How to use medications: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, -1, -1));

        medTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(medTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 300, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Issued Date:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        issusedDateTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(issusedDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 230, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Patient ID:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        idTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 300, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Exp Date:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        expDateTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(expDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Doctors NHS No: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        docNhsNumTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(docNhsNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 300, 40));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Daily Dose:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        dailyDoseTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(dailyDoseTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 230, -1));

        TabletComboBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TabletComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a selection", "Paracetamol", "Amlodipine", "Atesunate", "Ibuprofen" }));
        TabletComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TabletComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(TabletComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 230, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 120, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Doctor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 130, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("GP Appointment");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 140, 30));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Patient");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 140, 30));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("Payment");
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 130, 30));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setText("Pharmacy Office ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 130, 30));

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setText("Login");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1300, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Table", "Reference No. ", "Dose (mg)", "Number of Tables", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effect", "Further Information", "Storage Advice", "Administration", "Driving and Using Machine", "How to use medications", "Patient ID", "Doctors NHS No"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 1300, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    //when the comboBox component is pressed
    private void TabletComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TabletComboBoxActionPerformed
       //if item selected is Paracetamol       
        if (TabletComboBox.getSelectedItem().equals("Paracetamol"))  
        {
            //set the following text for each component 
            refTextField1.setText("pcl005875");
            doseTextField.setText("2");
            tabletTextField.setText("32");
            lotTextField.setText("561005875");
            issusedDateTextField.setText("27/02/2021");
            expDateTextField.setText("10/01/2022");
            dailyDoseTextField.setText("4");
            
            sideEffectTextField.setText("Dizzlling");
            infoTextField.setText("Place Dispensary");
            storageTextField.setText("Store in a cool place");
            adminTextField.setText("Yes actioned");
            machineTextField.setText("No");
            medTextField.setText("Use Water, no Alcohol");
            idTextField.setText("P001");
            docNhsNumTextField.setText("12345");
            
        }
        //else if item selected is Amlodipine       
        else if (TabletComboBox.getSelectedItem().equals("Amlodipine"))  //, Amlodipine, Atesunate, Ibuprofen
        {
            //set the following text for each component 
            refTextField1.setText("Aml05875");
            doseTextField.setText("2");
            tabletTextField.setText("32");
            lotTextField.setText("561005875");
            issusedDateTextField.setText("27/02/2021");
            expDateTextField.setText("10/01/2022");
            dailyDoseTextField.setText("4");
            
            sideEffectTextField.setText("Tiredness");
            infoTextField.setText("Place Dispensary");
            storageTextField.setText("Store in a cool place");
            adminTextField.setText("Yes actioned");
            machineTextField.setText("No");
            medTextField.setText("Use Water, no Alcohol");
            idTextField.setText("P001");
            docNhsNumTextField.setText("12345");
            
        }
         //else if item selected is Atesunate       
         else if (TabletComboBox.getSelectedItem().equals("Atesunate"))  //, Amlodipine, Atesunate, Ibuprofen
        {
                 //set the following text for each component 
            refTextField1.setText("Atl05875");
            doseTextField.setText("2");
            tabletTextField.setText("32");
            lotTextField.setText("564405875");
            issusedDateTextField.setText("27/02/2021");
            expDateTextField.setText("10/01/2022");
            dailyDoseTextField.setText("4");
            
            sideEffectTextField.setText("Coughing");
            infoTextField.setText("Place Dispensary");
            storageTextField.setText("Store in a cool place");
            adminTextField.setText("Yes actioned");
            machineTextField.setText("No");
            medTextField.setText("Use Water, no Alcohol");
            idTextField.setText("P001");
            docNhsNumTextField.setText("15545");
            
        }
                //else if item selected is Ibuprofen        
         else if (TabletComboBox.getSelectedItem().equals("Ibuprofen"))  //, Amlodipine, Atesunate, 
        {
           //set the following text for each component 
            refTextField1.setText("Ibl05875");
            doseTextField.setText("1");
            tabletTextField.setText("16");
            lotTextField.setText("54402875");
            issusedDateTextField.setText("27/02/2021");
            expDateTextField.setText("10/01/2022");
            dailyDoseTextField.setText("4");
            
            sideEffectTextField.setText("Sweating");
            infoTextField.setText("Place Dispensary");
            storageTextField.setText("Store in a cool place");
            adminTextField.setText("Yes actioned");
            machineTextField.setText("No");
            medTextField.setText("Use Water, no Alcohol");
            idTextField.setText("P002");
            docNhsNumTextField.setText("15565");
            
        }
         
         //else if item selected is Make a selection      
         else if (TabletComboBox.getSelectedItem().equals("Make a selection"))   
        {
           //set the following text for each component 
            refTextField1.setText("");
            doseTextField.setText("");
            tabletTextField.setText("");
            lotTextField.setText("");
            issusedDateTextField.setText("");
            expDateTextField.setText("");
            dailyDoseTextField.setText("");
            
            sideEffectTextField.setText("");
            infoTextField.setText("");
            storageTextField.setText("");
            adminTextField.setText("");
            machineTextField.setText("");
            medTextField.setText("");
            idTextField.setText("");
            docNhsNumTextField.setText("");
            
        }
        
        
    }//GEN-LAST:event_TabletComboBoxActionPerformed
        //Exit button component 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
//check if JOptionPane dialog box is a yes option which is 0
        if(JOptionPane.showConfirmDialog(null,"Confirm if you want to exit", "Pharmacy Management Systems", JOptionPane.YES_NO_OPTION) 
                  == JOptionPane.YES_NO_OPTION)
            //if yes, then exit the program
              System.exit(0);    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

        //when this button is pressed
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Login myLogin = new Login();  //create the object of class login
        myLogin.setVisible(true);    //show class login window
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); //downcasting the superclass variable of class JTable (jTable1) to the variable of the subclass (model)
        
      
       
         //annonymous inner class to add items to the table component 
        model.addRow( new Object[]
       {
         //add items from each component to the table component
            TabletComboBox.getSelectedItem().toString(),
            refTextField1.getText(),
            doseTextField.getText(),
            tabletTextField.getText(),
            lotTextField.getText(),
            issusedDateTextField.getText(),
            expDateTextField.getText(),
            dailyDoseTextField.getText(),
            sideEffectTextField.getText(),
            infoTextField.getText(),
            storageTextField.getText(),
            adminTextField.getText(),
            machineTextField.getText(),
            medTextField.getText(),
            idTextField.getText(),
            docNhsNumTextField.getText(),
       
       }
        
       
        );        
               
               
           
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refTextField1ActionPerformed

    //when delete button component is pressed
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();  //downcasting the superclass variable of class JTable (jTable1) to the variable of the subclass (model)
       if(jTable1.getSelectedRow() == -1)       //check if no row is selected by comparing it returned index to -1 
       {
           if(jTable1.getRowCount() == 0){      //check if the table has no row by comparing it with 0         
           
              //if these two conditions are true then print message on the JOptionPane 
           JOptionPane.showMessageDialog(null, "No data to delete", "Student Result System", JOptionPane.NO_OPTION );
           }
           else //if there are rows in the table, then print this using JOptionPane
               JOptionPane.showMessageDialog(null, "Select a row to delete", "Student Result System", JOptionPane.OK_OPTION);
       }
       else //if you have selected a row then remove it
           model.removeRow(jTable1.getSelectedRow());
           
       
    }//GEN-LAST:event_jButton3ActionPerformed

            //when this button is pressed
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Doctor myDoctor = new Doctor(); //create the object of class doctor
        myDoctor.setVisible(true);       //show class login window
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pharmacy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pharmacy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TabletComboBox;
    private javax.swing.JTextField adminTextField;
    private javax.swing.JTextField dailyDoseTextField;
    private javax.swing.JTextField docNhsNumTextField;
    private javax.swing.JTextField doseTextField;
    private javax.swing.JTextField expDateTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField infoTextField;
    private javax.swing.JTextField issusedDateTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lotTextField;
    private javax.swing.JTextField machineTextField;
    private javax.swing.JTextField medTextField;
    private javax.swing.JTextField refTextField1;
    private javax.swing.JTextField sideEffectTextField;
    private javax.swing.JTextField storageTextField;
    private javax.swing.JTextField tabletTextField;
    // End of variables declaration//GEN-END:variables
}
